const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/db');

const Ticket = sequelize.define('Ticket', {
  id: {
    type: DataTypes.INTEGER,
    autoIncrement: true,
    primaryKey: true,
  },
  ticketNumber: {
    type: DataTypes.STRING(20),
    allowNull: true, // Allow null because it's auto-generated by database trigger
    unique: true,
    field: 'ticket_number'
  },
  title: {
    type: DataTypes.STRING(255),
    allowNull: false,
  },
  description: {
    type: DataTypes.TEXT,
    allowNull: true,
  },
  status: {
    type: DataTypes.ENUM('open', 'in_progress', 'resolved', 'closed', 'on_hold'),
    defaultValue: 'open',
    allowNull: false,
  },
  priority: {
    type: DataTypes.ENUM('low', 'medium', 'high', 'urgent'),
    defaultValue: 'medium',
    allowNull: false,
  },
  type: {
    type: DataTypes.ENUM('bug', 'feature_request', 'support', 'question', 'task', 'incident'),
    defaultValue: 'support',
    allowNull: false,
  },
  tags: {
    type: DataTypes.JSON,
    defaultValue: [],
    allowNull: true,
  },
  companyId: {
    type: DataTypes.INTEGER,
    field: 'company_id',
    allowNull: false,
    references: {
      model: 'companies',
      key: 'id',
    },
  },
  contactId: {
    type: DataTypes.INTEGER,
    field: 'contact_id',
    allowNull: true,
    references: {
      model: 'contacts',
      key: 'id',
    },
  },
  assignedTo: {
    type: DataTypes.INTEGER,
    field: 'assigned_to',
    allowNull: true,
    references: {
      model: 'users',
      key: 'id',
    },
  },
  createdBy: {
    type: DataTypes.INTEGER,
    field: 'created_by',
    allowNull: false,
    references: {
      model: 'users',
      key: 'id',
    },
  },
  // Related entities (optional)
  relatedLeadId: {
    type: DataTypes.INTEGER,
    field: 'related_lead_id',
    allowNull: true,
    references: {
      model: 'leads',
      key: 'id',
    },
  },
  relatedOpportunityId: {
    type: DataTypes.INTEGER,
    field: 'related_opportunity_id',
    allowNull: true,
    references: {
      model: 'opportunities',
      key: 'id',
    },
  },
  relatedSaleId: {
    type: DataTypes.INTEGER,
    field: 'related_sale_id',
    allowNull: true,
    references: {
      model: 'sales',
      key: 'id',
    },
  },
  relatedTaskId: {
    type: DataTypes.INTEGER,
    field: 'related_task_id',
    allowNull: true,
    references: {
      model: 'tasks',
      key: 'id',
    },
  },
  // Timestamps
  resolvedAt: {
    type: DataTypes.DATE,
    field: 'resolved_at',
    allowNull: true,
  },
  closedAt: {
    type: DataTypes.DATE,
    field: 'closed_at',
    allowNull: true,
  },
  // Metadata
  estimatedHours: {
    type: DataTypes.DECIMAL(5, 2),
    field: 'estimated_hours',
    allowNull: true,
  },
  actualHours: {
    type: DataTypes.DECIMAL(5, 2),
    field: 'actual_hours',
    allowNull: true,
  },
  resolutionNotes: {
    type: DataTypes.TEXT,
    field: 'resolution_notes',
    allowNull: true,
  },
  // Archive fields
  archived: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
    allowNull: false,
  },
  archivedAt: {
    type: DataTypes.DATE,
    field: 'archived_at',
    allowNull: true,
  },
}, {
  tableName: 'tickets',
  timestamps: true,
  createdAt: 'created_at',
  updatedAt: 'updated_at',
  indexes: [
    {
      fields: ['company_id']
    },
    {
      fields: ['contact_id']
    },
    {
      fields: ['assigned_to']
    },
    {
      fields: ['created_by']
    },
    {
      fields: ['status']
    },
    {
      fields: ['priority']
    },
    {
      fields: ['type']
    },
    {
      fields: ['ticket_number']
    },
    {
      fields: ['created_at']
    },
    {
      fields: ['related_lead_id']
    },
    {
      fields: ['related_opportunity_id']
    },
    {
      fields: ['related_sale_id']
    },
    {
      fields: ['related_task_id']
    }
  ]
});

// Virtual field for formatted ticket number display
Ticket.prototype.getDisplayNumber = function() {
  return this.ticketNumber;
};

// Virtual field to check if ticket is open
Ticket.prototype.isOpen = function() {
  return ['open', 'in_progress', 'on_hold'].includes(this.status);
};

// Virtual field to check if ticket is resolved
Ticket.prototype.isResolved = function() {
  return ['resolved', 'closed'].includes(this.status);
};

// Virtual field to get status badge color
Ticket.prototype.getStatusColor = function() {
  const colors = {
    open: 'blue',
    in_progress: 'yellow',
    resolved: 'green',
    closed: 'gray',
    on_hold: 'orange'
  };
  return colors[this.status] || 'gray';
};

// Virtual field to get priority badge color
Ticket.prototype.getPriorityColor = function() {
  const colors = {
    low: 'green',
    medium: 'yellow',
    high: 'orange',
    urgent: 'red'
  };
  return colors[this.priority] || 'gray';
};

// Hook to generate ticket number if not provided (fallback for database trigger)
Ticket.beforeCreate(async (ticket, options) => {
  if (!ticket.ticketNumber) {
    // Get company to generate ticket number
    const Company = require('./Company');
    const company = await Company.findByPk(ticket.companyId);
    
    if (company) {
      // Get company prefix (first 3 letters of company name, uppercase)
      const companyPrefix = company.name.substring(0, 3).toUpperCase();
      
      // Get next ticket number for this company
      const { sequelize } = require('../config/db');
      const [results] = await sequelize.query(
        'SELECT COALESCE(MAX(CAST(SUBSTRING(ticket_number FROM \'[0-9]+$\') AS INTEGER)), 0) + 1 as next_num FROM tickets WHERE company_id = ?',
        {
          replacements: [ticket.companyId],
          type: sequelize.QueryTypes.SELECT
        }
      );
      
      const nextNum = results.next_num || 1;
      const currentYear = new Date().getFullYear();
      
      // Generate ticket number: COMPANY-YYYY-NNNNNN
      ticket.ticketNumber = `${companyPrefix}-${currentYear}-${String(nextNum).padStart(6, '0')}`;
    }
  }
});

module.exports = Ticket;